<a href="https://colab.research.google.com/github/zarfshankhan/Neuro-Nova-AI-project/blob/main/Practice_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Conditional statement

In [ ]:
Height=int (input("Enter your height"))
if (Height <= 100):
  print ("you are tall")
elif (Height >=100 and Height <= 200):
  print ("you are not tall")
else:
  print ("You're not tall enough to ride, but maybe next year!")

Enter your height30
you are tall


In [ ]:
A= int(input("Enter the Positive number;"))

if (A >= 0):
   print ( "The number is positive")
elif(A <= 0) :
    print ( "The number is Negative")
else:
  print ("Enter the number")

Enter the Positive number;-4
The number is Negative


In [ ]:
n= input("what is your name;")
if (n == "zarfshan"):
  print ("unique Name")
elif (n != "zarfshan"):
  print ("not unique Name")
else:
  print ("hello: zarfshan")

what is your name;musfera
not unique Name


In [ ]:

n= input ("enter the table:")
if (n += "2"):
  print ("table of" n)


Loops

In [ ]:
secret_Num= 15

while True:
    guess = int(input("Guess secret no :"))
    if(guess < secret_Num):
          print(" less than Secret_num")
    elif(guess > secret_Num):
          print(" greater than Secret_num")
    else:
          print("Conguralation this Secret_num")
          break;
    secret_Num +=1





Guess secret no :15
Conguralation this Secret_num


practice 1

In [ ]:
# Grocery Bill Calculator

apple_qty = 3
apple_price = 2

banana_qty = 2
banana_price = 1

total_bill = (apple_qty * apple_price) + (banana_qty * banana_price)

print("Total Bill = $", total_bill)

Total Bill = $ 8


In [ ]:
# Student Age Check

age = 18

if age >= 18:
    print("Eligible for driving license")
else:
    print("Not eligible for driving license")

Eligible for driving license


In [ ]:
# Swap Two Numbers

ahmed = 10
ali = 20

print("Before Swap")
print("Ahmed =", ahmed)
print("Ali =", ali)

ahmed, ali = ali, ahmed

print("\nAfter Swap")
print("Ahmed =", ahmed)
print("Ali =", ali)

Before Swap
Ahmed = 10
Ali = 20

After Swap
Ahmed = 20
Ali = 10


In [ ]:
# Smart Login System

username = "admin"
password = "1234"

entered_username = "admin"
entered_password = "1234"

if entered_username == username and entered_password == password:
    print("Login Successful")
else:
    print("Invalid Username or Password")

Login Successful


In [ ]:
# Product Discount Checker

amount = 500

if amount > 300:
    discount = amount * 0.10
    final_amount = amount - discount
    print("Discount = $", discount)
    print("Final Amount = $", final_amount)
else:
    print("No Discount")
    print("Final Amount = $", amount)

Discount = $ 50.0
Final Amount = $ 450.0


In [ ]:
# Memory Identity Challenge

a = 100
b = 100

print("a =", a)
print("b =", b)

print("ID of a:", id(a))
print("ID of b:", id(b))

print("Same Memory?", id(a) == id(b))

# Change one variable
b = 200

print("\nAfter Changing b")

print("a =", a)
print("b =", b)

print("ID of a:", id(a))
print("ID of b:", id(b))

print("Same Memory?", id(a) == id(b))

a = 100
b = 100
ID of a: 11648520
ID of b: 11648520
Same Memory? True

After Changing b
a = 100
b = 200
ID of a: 11648520
ID of b: 11651720
Same Memory? False


In [ ]:
Practice 2

In [ ]:
# Even or Odd Checker

number = int(input("Enter a number: "))

if number % 2 == 0:
    print("The number is Even")
else:
    print("The number is Odd")

Enter a number: 56
The number is Even


In [ ]:
# Simple Login Attempts

password = input("Enter Password: ")

if password == "python123":
    print("Access Granted")
else:
    print("Access Denied")

Enter Password: 456
Access Denied


In [ ]:
# Multiplication Table

number = int(input("Enter a number: "))

for i in range(1, 11):
    print(number, "x", i, "=", number * i)

Enter a number: 2
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [ ]:
# Number Guessing Game

secret = 7
attempts = 3

while attempts > 0:
    guess = int(input("Guess the number: "))

    if guess == secret:
        print("You Win")
        break
    else:
        attempts -= 1
        print("Wrong Guess!")
        print("Attempts Left:", attempts)

if attempts == 0:
    print("Game Over")

Guess the number: 7
You Win


In [ ]:
# ATM Withdrawal System

balance = float(input("Enter Your Balance: "))

while True:
    withdraw = float(input("Enter Withdrawal Amount (0 to Exit): "))

    if withdraw == 0:
        print("Thank You!")
        break

    elif withdraw > balance:
        print("Insufficient Balance")

    else:
        balance = balance - withdraw
        print("Remaining Balance =", balance)

Enter Your Balance: 5
Enter Withdrawal Amount (0 to Exit): 2
Remaining Balance = 3.0
Enter Withdrawal Amount (0 to Exit): 2
Remaining Balance = 1.0
Enter Withdrawal Amount (0 to Exit): 1
Remaining Balance = 0.0
Enter Withdrawal Amount (0 to Exit): 1
Insufficient Balance
Enter Withdrawal Amount (0 to Exit): 1
Insufficient Balance
Enter Withdrawal Amount (0 to Exit): 0
Thank You!


In [ ]:
# Student Result Analyzer

total = 0
fail = False

for i in range(1, 6):
    marks = int(input("Enter marks for Subject " + str(i) + ": "))

    total += marks

    if marks < 40:
        fail = True

average = total / 5

print("Total Marks =", total)
print("Average =", average)

if fail:
    print("Grade: Fail")
elif average >= 80:
    print("Grade: A")
elif average >= 60:
    print("Grade: B")
elif average >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Enter marks for Subject 1: 70
Enter marks for Subject 2: 57
Enter marks for Subject 3: 98
Enter marks for Subject 4: 98
Enter marks for Subject 5: 79
Total Marks = 402
Average = 80.4
Grade: A


list

In [ ]:
list=('apple','banana','orange','kiwi','watermelon')
print(list[0:4])
print(list[1:2])
print(list[3:5])
print(list[:4])
print(list[1:])
print(list[-1:4])
print(list[:-4])
print( type(list))

('apple', 'banana', 'orange', 'kiwi')
('banana',)
('kiwi', 'watermelon')
('apple', 'banana', 'orange', 'kiwi')
('banana', 'orange', 'kiwi', 'watermelon')
()
('apple',)
<class 'tuple'>


PRACTICE 3

In [ ]:

# Grocery Bill Calculator

milk_packs = 3
milk_price = 4

bread_packs = 2
bread_price = 2

total_bill = (milk_packs * milk_price) + (bread_packs * bread_price)

print("Total Bill = $", total_bill)

Total Bill = $ 16


In [ ]:
# Student Result Checker
mark =35
if mark >= 40:
  print("pass")
else:
  print("fail")

fail


In [ ]:
# Favorite Fruits List

fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"]

print("First Fruit:", fruits[0])
print("Last Fruit:", fruits[-1])

fruits.append("Pineapple")

print("Updated List:", fruits)

First Fruit: Apple
Last Fruit: Grapes
Updated List: ['Apple', 'Banana', 'Mango', 'Orange', 'Grapes', 'Pineapple']


In [ ]:
# Fixed Exam Subjects

subjects = ("English", "Mathematics", "Physics", "Chemistry", "Computer Science")

print(subjects[0])
print(subjects[1])
print(subjects[2])
print(subjects[3])
print(subjects[4])

English
Mathematics
Physics
Chemistry
Computer Science


In [ ]:
# Employee Information Dictionary

employee = {
    "empID": 101,
    "employee name": "Zarfshan Khan",
    "age": 28,
    "salary": 50000,
    "designation": "Software Engineer",
    "join date": "10-01-2024"
}

print(employee["empID"])
print(employee["employee name"])
print(employee["age"])
print(employee["salary"])
print(employee["designation"])
print(employee["join date"])

In [ ]:
# Online Shopping Discount

customer_bill = 600
discount_percentage = 15

if customer_bill > 500:
    discount = (customer_bill * discount_percentage) / 100
else:
    discount = 0

final_amount = customer_bill - discount

print("Customer Bill = $", customer_bill)
print("Discount = $", discount)
print("Final Payable Amount = $", final_amount)

Customer Bill = $ 600
Discount = $ 90.0
Final Payable Amount = $ 510.0


In [ ]:
# Unique Classroom Attendance

students = {"Ali", "Ahmed", "Sara", "Ayesha"}
student=list(students)
student.append("arqam")

print(students)

{'Ali', 'Ayesha', 'Ahmed', 'Sara'}


In [ ]:
# Mobile Store System

mobiles = {
    "Samsung": 900,
    "iPhone": 1500,
    "Oppo": 700
}

# Add a new mobile
mobiles["Vivo"] = 650

# Update existing price
mobiles["Samsung"] = 950

# Print all data
print(mobiles)

{'Samsung': 950, 'iPhone': 1500, 'Oppo': 700, 'Vivo': 650}


In [ ]:
# Temperature Analyzer Function

def check_temperature(temp):
    if temp > 35:
        return "Hot"
    else:
        return "Cold"

result = check_temperature(38)
print(result)

Hot


In [ ]:
# Salary Bonus Function

def calculate_bonus(salary):
    if salary > 50000:
        bonus = salary * 0.20
    else:
        bonus = salary * 0.10
    return bonus

print("Bonus =", calculate_bonus(60000))
print("Bonus =", calculate_bonus(40000))

Bonus = 12000.0
Bonus = 4000.0


In [ ]:
# Football Match Statistics

scores = [2, 5, 1, 3, 4]

highest = max(scores)
lowest = min(scores)
average = sum(scores) / len(scores)

print("Highest Score:", highest)
print("Lowest Score:", lowest)
print("Average Score:", average)

Highest Score: 5
Lowest Score: 1
Average Score: 3.0


In [ ]:
# Common Skills Checker

student1 = {"Python", "C++", "Java", "HTML"}
student2 = {"Python", "Java", "JavaScript", "CSS"}

common = student1 & student2
unique = student1 ^ student2

print("Common Skills:", common)
print("Unique Skills:", unique)

Common Skills: {'Java', 'Python'}
Unique Skills: {'HTML', 'CSS', 'C++', 'JavaScript'}


In [ ]:
# Student Record Function

def student_record(name, marks):
    if marks >= 50:
        return "Pass"
    else:
        return "Fail"

print(student_record("Ali", 70))
print(student_record("Sara", 45))

Pass
Fail


In [ ]:
# Product Price Updater

products = {
    "Laptop": 800,
    "Mouse": 20,
    "Keyboard": 50
}

for item in products:
    products[item] += products[item] * 0.10

print(products)

{'Laptop': 880.0, 'Mouse': 22.0, 'Keyboard': 55.0}


In [ ]:
# Lambda Function Calculator

add = lambda a, b: a + b
sub = lambda a, b: a - b
mul = lambda a, b: a * b
div = lambda a, b: a / b
mod = lambda a, b: a % b
square = lambda a: a ** 2

print( "Adittion:" , add(10, 5))
print("Subtraction:", sub(10, 5))
print("Multiplication:", mul(10, 5))
print("Division:", div(10, 5))
print("Modulus:", mod(10, 5))
print("Square:", square(10))

Adittion: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
Modulus: 0
Square: 100


In [ ]:
# Smart Banking System

def withdraw(balance, amount):
    if amount <= balance:
        balance -= amount
        return balance
    else:
        return "Insufficient Balance"

print(withdraw(1000, 400))
print(withdraw(1000, 600))

600
400


In [ ]:
# Employee Data Analyzer

employees = {
    "Ali": 50000,
    "Sara": 70000,
    "Ahmed": 60000,
    "Ayesha": 55000
}

highest = max(employees.values())
lowest = min(employees.values())
average = sum(employees.values()) / len(employees)

highest_employee = max(employees, key=employees.get)

print("Highest Salary:", highest)
print("Lowest Salary:", lowest)
print("Average Salary:", average)
print("Employee with Maximum Salary:", highest_employee)

Highest Salary: 70000
Lowest Salary: 50000
Average Salary: 58750.0
Employee with Maximum Salary: Sara


In [ ]:
# Online Course Enrollment System

courses = ["Python", "Java", "Web Development"]

students = {"Ali", "Sara", "Ahmed"}

enrollment = {
    "Ali": "Python",
    "Sara": "Java",
    "Ahmed": "Web Development"
}

print("Courses:", courses)
print("Students:", students)
print("Enrollment Report:")

for student, course in enrollment.items():
    print(student, "->", course)

Courses: ['Python', 'Java', 'Web Development']
Students: {'Ahmed', 'Ali', 'Sara'}
Enrollment Report:
Ali -> Python
Sara -> Java
Ahmed -> Web Development


In [ ]:
#grade marks
grade = lambda marks : "A" if marks >=80 else ("B" if marks >= 60 else "C")
print(grade(65))

B


In [ ]:
# complete students management system
def mini_system():
  student={
   "musfera" : 89,
    "Arshiq": 78,
   "Zartash": 98,
   "ahmad":67}

## **OOP**

In [ ]:
class Employee:
  def __init__(self, name, id , position, salary):
        self.name = name
        self.id = id
        self.position = position
        self.salary = salary



p1 = Employee("zar", 12 , "manager", 250000)
p2 = Employee("musfera", 23," engineer", 350000)


print(p1.name)
print(p1.id)
print(p1.position)
print(p1.salary)
print(p2.name)
print(p2.id)
print(p2.salary)
print(p2.position)

zar
12
manager
250000
musfera
23
350000
 engineer


# **Inheritance**

In [ ]:
class Animal:
  def show(self):
    print("Animal class")
class insect(Animal):
  pass
c = insect()
c.show()

Animal class


# **Encapsulation**

In [ ]:
class Account:
    def __init__(self, name, balance):
        self.name = name
        self.__balance = balance

    def check_balance(self):
        print("Balance:", self.__balance)

    def deposit(self, amount):
        self.__balance += amount
        print("Deposit Successful")

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            print("Withdrawal Successful")
        else:
            print("Insufficient Balance")


class ATM(Account):
    pass


user = ATM("Musfera", 20000)

user.check_balance()
user.deposit(5000)
user.check_balance()
user.withdraw(3000)
user.check_balance()

Balance: 20000
Deposit Successful
Balance: 25000
Withdrawal Successful
Balance: 22000


# **user input**

In [ ]:
class Account:
    def __init__(self, registration, name, balance):
        self.registration = registration
        self.name = name
        self.__balance = balance   # Private variable

    # Getter
    def get_balance(self):
        return self.__balance

    # Setter
    def set_balance(self, balance):
        if balance >= 0:
            self.__balance = balance
        else:
            print("Invalid Balance")

    # Display Details
    def display(self):
        print("\nAccount Details")
        print("Registration No:", self.registration)
        print("Name:", self.name)
        print("Balance:", self.__balance)


# User Input
registration = input("Enter Registration Number: ")
name = input("Enter Your Name: ")
balance = float(input("Enter Your Balance: "))

user = Account(registration, name, balance)

user.display()

new_balance = float(input("\nEnter New Balance: "))
user.set_balance(new_balance)

print("\nUpdated Balance:", user.get_balance())

Enter Registration Number: 123
Enter Your Name: zarfshan
Enter Your Balance: 200000

Account Details
Registration No: 123
Name: zarfshan
Balance: 200000.0

Enter New Balance: 120000

Updated Balance: 120000.0


# **PIN**

In [ ]:
class Account:
    def __init__(self, name, pin, balance):
        self.name = name
        self.__pin = pin
        self.__balance = balance

    def check_pin(self, pin):
        if pin == self.__pin:
            return True
        else:
            return False

    def get_balance(self):
        return self.__balance

    def set_balance(self, balance):
        if balance >= 0:
            self.__balance = balance
        else:
            print("Invalid Balance")


class Atm(Account):
    def deposit(self, amount):
        self.set_balance(self.get_balance() + amount)
        print("Deposit Successful")

    def withdraw(self, amount):
        if amount <= self.get_balance():
            self.set_balance(self.get_balance() - amount)
            print("Withdrawal Successful")
        else:
            print("Insufficient Balance")


name = input("Enter Your Name: ")
pin = int(input("Set Your 4-digit PIN: "))
balance = float(input("Enter Initial Balance: "))

user = Atm(name, pin, balance)

enter_pin = int(input("Enter Your PIN: "))

if user.check_pin(enter_pin):
    print("PIN Verified")
    print("Current Balance:", user.get_balance())

    choice = input("Enter your choice (Deposit/Withdraw): ")

    if choice == "Deposit":
        amount = float(input("Enter Deposit Amount: "))
        user.deposit(amount)

    elif choice == "Withdraw":
        amount = float(input("Enter Withdraw Amount: "))
        user.withdraw(amount)

    else:
        print("Invalid Choice")

    print("Updated Balance:", user.get_balance())

else:
    print("Incorrect PIN")

Enter Your Name: ZARFAHAN
Set Your 4-digit PIN: 1234
Enter Initial Balance: 20000
Enter Your PIN: 1234
PIN Verified
Current Balance: 20000.0
Enter your choice (Deposit/Withdraw): Deposit
Enter Deposit Amount: 2000
Deposit Successful
Updated Balance: 22000.0


**Abstraction:**
Abstraction means hiding the implementation details and showing only the essential features to the user.

In Python, abstraction is implemented using the built-in abc (Abstract Base Class) module.

In [ ]:
from abc import ABC, abstractmethod

class Payment(ABC):
    @abstractmethod
    def pay(self, amount):
        pass

class CreditCard(Payment):
    def pay(self, amount):
        print("Payment of Rs.", amount, "made using Credit Card.")

class EasyPaisa(Payment):
    def pay(self, amount):
        print("Payment of Rs.", amount, "made using EasyPaisa.")

class JazzCash(Payment):
    def pay(self, amount):
        print("Payment of Rs.", amount, "made using JazzCash.")

print("1. Credit Card")
print("2. EasyPaisa")
print("3. JazzCash")

choice = input("Choose Payment Method (1/2/3): ")
amount = float(input("Enter Amount: "))

if choice == "1":
    user = CreditCard()
elif choice == "2":
    user = EasyPaisa()
elif choice == "3":
    user = JazzCash()
else:
    print("Invalid Choice")
    exit()

user.pay(amount)

1. Credit Card
2. EasyPaisa
3. JazzCash
Choose Payment Method (1/2/3): 1
Enter Amount: 2000
Payment of Rs. 2000.0 made using Credit Card.


# **Polymorphisum**

In [ ]:
class Animal:
  def sound(self):
     print  ("same sound")
class Dog (Animal):
  def sound(self):
    print ("Bark")
d = Dog()
d.sound()

Bark
Meow


In [ ]:
class Animal:
    def __init__(self, name):
        self.name = name

    def sound(self):
        print("Some sound")

    def eat(self):
        print(self.name, "is eating.")

    def sleep(self):
        print(self.name, "is sleeping.")


class Dog(Animal):
    def __init__(self, name):
      super().__init__(name)

    def eat(self):
        print(self.name, "is eating.")

    def sleep(self):
        print(self.name, "is sleeping.")
    def sound(self):
        print(self.name, "says: Bark")


class Cat(Animal):
  def __init__(self, name):
      super().__init__(name)

  def eat(self):
        print(self.name, "is eating.")

  def sleep(self):
        print(self.name, "is sleeping.")

  def sound(self):
        print(self.name, "says: Meow")

animal = input("Enter animal (Dog/Cat): ")
name = input("Enter animal name: ")

if animal == "Dog":
    obj = Dog(name)
    obj.sound()
    obj.eat()
    obj.sleep()
elif animal == "Cat":
    obj = Cat(name)
    obj.sound()
    obj.eat()
    obj.sleep()
else:
    print("Invalid animal!")
    exit()


Enter animal (Dog/Cat): Dog
Enter animal name: maxi
maxi says: Bark
maxi is eating.
maxi is sleeping.


**Dunder Method:**
Special methods jaise str, len etc built-in behavior control karte hain.
Dunder means Double UNDERscore. These are special methods that start and end with __.

**Example:**

__init__
__str__
__len__
__add__

They allow you to customize how objects behave.
Dunder methods (Double UNDERscore methods) aise special methods hain jo Python ke operators ko control karte hain. Jaisey +, -, *, ==, etc.

**Common Dunder Methods:**

__init__ - Constructor
__str__ - String representation
__add__ - Addition operator (+)
__sub__ - Subtraction operator (-)
__mul__ - Multiplication operator (*)
__eq__ - Equality operator (==)
__lt__ - Less than operator (<)
__len__ - Length function


1. __init__()** (Constructor)**

In [ ]:
class Student:
    def __init__(self, name):
        self.name = name

s = Student("Ali")
print(s.name)

Ali


2. __str__() **(String Representation)**

In [ ]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"Name: {self.name}, Age: {self.age}"

name = input("Enter Name: ")
age = int(input("Enter Age: "))

s = Student(name, age)
print(s)

Enter Name: ZARFSHAN
Enter Age: 22
Name: ZARFSHAN, Age: 22


. __len__()

In [ ]:
class Student:
    def __init__(self, name):
        self.name = name

    def __len__(self):
        return len(self.name)

name = input("Enter Name: ")

s = Student(name)
print("Length:", len(s))

Enter Name: ZARFSAN
Length: 7


4.Methods:
 __add__(),**sub,mul,equatioon

In [ ]:
class Number:
    def __init__(self, value):
        self.value = value

    def __add__(self, other):
        return self.value + other.value

    def __sub__(self, other):
        return self.value - other.value

    def __mul__(self, other):
        return self.value * other.value

    def __truediv__(self, other):
        return self.value / other.value

    def __eq__(self, other):
        return self.value == other.value

    def __lt__(self, other):
        return self.value < other.value

    def __gt__(self, other):
        return self.value > other.value

    def __le__(self, other):
        return self.value <= other.value


num1 = int(input("Enter First Number: "))
num2 = int(input("Enter Second Number: "))

n1 = Number(num1)
n2 = Number(num2)

print("\nChoose an Operation")
print("+  Addition")
print("-  Subtraction")
print("*  Multiplication")
print("/  Division")
print("== Equal")
print("<  Less Than")
print(">  Greater Than")
print("<= Less Than or Equal To")

choice = input("Enter your choice: ")

if choice == "+":
    print("Answer =", n1 + n2)

elif choice == "-":
    print("Answer =", n1 - n2)

elif choice == "*":
    print("Answer =", n1 * n2)

elif choice == "/":
    if num2 != 0:
        print("Answer =", n1 / n2)
    else:
        print("Cannot divide by zero.")

elif choice == "==":
    print("Answer =", n1 == n2)

elif choice == "<":
    print("Answer =", n1 < n2)

elif choice == ">":
    print("Answer =", n1 > n2)

elif choice == "<=":
    print("Answer =", n1 <= n2)

else:
    print("Invalid Choice")

Enter First Number: 5
Enter Second Number: 6

Choose an Operation
+  Addition
-  Subtraction
*  Multiplication
/  Division
== Equal
<  Less Than
>  Greater Than
<= Less Than or Equal To
Enter your choice: =
Invalid Choice


### **numpy**

In [ ]:
import numpy as np

arr = np.array([[[[1, 2, 3, 4, 5],[2,4,6,7,8],[3,4,6,7,8],[2,3,5,8,9]]]])
print(arr[0,0, 0:4,2:5])
print(arr.shape)

print(arr)

[[3 4 5]
 [6 7 8]
 [6 7 8]
 [5 8 9]]
(1, 1, 4, 5)
[[[[1 2 3 4 5]
   [2 4 6 7 8]
   [3 4 6 7 8]
   [2 3 5 8 9]]]]


# *NumPy Creating Arrays*
**1D Array**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

**2D** **Array**

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3D Array

In [ ]:
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array indexsing

In [ ]:
import numpy as np

# arr = np.array([10, 20, 30, 40, 50])

# print(arr[0])    # First element
# print(arr[2])    # Third element
# print(arr[-1])   # Last element

# ##2D Array

# arr = np.array([[1, 2, 3],
#                 [4, 5, 6]])

# print(arr[0, 1])   # 2
# print(arr[1, 2])   # 6

#3D Array###============================================================================================================
arr = np.array([[[1,3,4],[2,4,7],[3,5,6]]])
print(arr[0,0,1])
print (arr[0,1,1])


3
4


Array Slicing

In [ ]:
import numpy as np

# ==========================================
# NUMPY ARRAY SLICING (1D, 2D, 3D)
# ==========================================

# -------------------------
# 1D Array Slicing
# -------------------------
arr1 = np.array([10, 20, 30, 40, 50, 60])

print("========== 1D ARRAY ==========")
print("Original Array:", arr1)

print("arr1[1:4]   =", arr1[1:4])      # 20 30 40
print("arr1[:3]    =", arr1[:3])       # 10 20 30
print("arr1[2:]    =", arr1[2:])       # 30 40 50 60
print("arr1[-3:-1] =", arr1[-3:-1])    # 40 50
print("arr1[::2]   =", arr1[::2])      # 10 30 50

# -------------------------
# 2D Array Slicing
# -------------------------
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("\n========== 2D ARRAY ==========")
print("Original Array:\n", arr2)

print("\nFirst Two Rows:")
print(arr2[0:2])

print("\nFirst Row:")
print(arr2[0])

print("\nSecond Column:")
print(arr2[:, 1])

print("\nFirst Two Rows, Last Two Columns:")
print(arr2[0:2, 1:3])

print("\nLast Two Rows:")
print(arr2[1:3])

# -------------------------
# 3D Array Slicing
# -------------------------
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("\n========== 3D ARRAY ==========")
print("Original Array:\n", arr3)

print("\nFirst 2D Array:")
print(arr3[0])

print("\nSecond 2D Array:")
print(arr3[1])

print("\nFirst Row of First 2D Array:")
print(arr3[0, 0])

print("\nElement 6:")
print(arr3[1, 0, 1])

print("\nFirst Column from Both 2D Arrays:")
print(arr3[:, :, 0])

print("\nSecond Row from Both 2D Arrays:")
print(arr3[:, 1, :])

========== 1D ARRAY ==========
Original Array: [10 20 30 40 50 60]
arr1[1:4]   = [20 30 40]
arr1[:3]    = [10 20 30]
arr1[2:]    = [30 40 50 60]
arr1[-3:-1] = [40 50]
arr1[::2]   = [10 30 50]

========== 2D ARRAY ==========
Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First Two Rows:
[[1 2 3]
 [4 5 6]]

First Row:
[1 2 3]

Second Column:
[2 5 8]

First Two Rows, Last Two Columns:
[[2 3]
 [5 6]]

Last Two Rows:
[[4 5 6]
 [7 8 9]]

========== 3D ARRAY ==========
Original Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

First 2D Array:
[[1 2]
 [3 4]]

Second 2D Array:
[[5 6]
 [7 8]]

First Row of First 2D Array:
[1 2]

Element 6:
6

First Column from Both 2D Arrays:
[[1 3]
 [5 7]]

Second Row from Both 2D Arrays:
[[3 4]
 [7 8]]


**Reshape**

In [ ]:
import numpy as np
#1D TO 2D

arr = np.array([1,2,3,4,5,6])

newarr = arr.reshape(2,3)

print(newarr)
# 1D TO 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)

print(newarr)


[[1 2 3]
 [4 5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**JOIN** **ARRAY**

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)
#JOIN 2D ARRAY


arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

copy & view

In [ ]:
#copy#
import numpy as np

arr = np.array([[1, 2, 3],[1, 4, 5]])
x = arr.copy()
arr[0,1] = 42
arr[1,2]=15

print(arr)
print(x)

#view ##
arr = np.array([[[2,1],[2,3], [2, 3]]])
x = arr.view()
arr[0,1,1] = 12

print(arr)
print(x)

[[[ 2  1]
  [ 2 12]
  [ 2  3]]]
[[[ 2  1]
  [ 2 12]
  [ 2  3]]]


ITERATING

In [ ]:

import numpy as np

arr= np. array([[1,5,5],[2,4,7]])
#arr = np.array([[[1, 2, 3],[1,5,3] ,[4, 5, 6]]])

for x in arr:
  for y in x:

      print(y)



1
5
5
2
4
7


SPLIT ARRAY

In [ ]:
import numpy as np
#arr = np.array([1,2,3,4,5,6])

arr = np.array([[1, 2, 3],[ 4, 5, 6]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


Search

Sort

Filter

# **Pandas**

In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


# **Series**

In [ ]:
import pandas as pd

a = [1, 7, 2]
b = [2, 4, 6]

myvar = pd.Series(a)==============================================================================================
myvar = pd.Series(b)

print(myvar)

0    2
1    4
2    6
dtype: int64


# **label**

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


## **Data** **Frame**

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45],
  "age": [80 ,90 ,70]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)
#locate row
print(df.loc[0,1])

print(df)

calories    420
duration     50
age          80
Name: 0, dtype: int64
   calories  duration  age
0       420        50   80
1       380        40   90
2       390        45   70


# **Name** **indexsing**

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
df = pd.DataFrame(data, index = ["1", "2", "3"])


print(df)

   calories  duration
1       420        50
2       380        40
3       390        45


CSV and json

In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')
#JSON
df = pd.read_json('data.json')

print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


cleaning data

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", None, "Ahmed"],
    "Age": [20, 22, None]
}

df = pd.DataFrame(data)

print(df)

print(df.dropna())

    Name   Age
0    Ali  20.0
1   None  22.0
2  Ahmed   NaN
  Name   Age
0  Ali  20.0


# **Cleaning Empty cell**

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", None, "Ahmed"],
    "Age": [20, None, 21]
}

df = pd.DataFrame(data)

df.fillna(0, inplace=True)

print(df)

    Name   Age
0    Ali  20.0
1      0   0.0
2  Ahmed  21.0


# **Cleaning Wrong Format**

In [ ]:
import pandas as pd

data = {
    "Date": ["2024/01/01", "2024/02/15", "2024/03/20"]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

print(df)

        Date
0 2024-01-01
1 2024-02-15
2 2024-03-20


# **Cleaning Wrong Data**

In [ ]:
import pandas as pd

data = {
    "Age": [20, 25, 200, 22]
}

df = pd.DataFrame(data)

df.loc[df["Age"] > 100, "Age"] = 25

print(df)

   Age
0   20
1   25
2   25
3   22


# **Removing Duplication**

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ali", "Ahmed"],
    "Marks": [85, 90, 85, 88]
}

df = pd.DataFrame(data)

print("Original Data")
print(df)

df = df.drop_duplicates()

print("\nAfter Removing Duplicates")
print(df)

Original Data
    Name  Marks
0    Ali     85
1   Sara     90
2    Ali     85
3  Ahmed     88

After Removing Duplicates
    Name  Marks
0    Ali     85
1   Sara     90
3  Ahmed     88
